'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")>  _
    Partial Friend NotInheritable Class RepositorySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As RepositorySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New RepositorySettings()),RepositorySettings)
        
        Public Shared ReadOnly Property [Default]() As RepositorySettings
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RepositoryFolderPath() As String
            Get
                Return CType(Me("RepositoryFolderPath"),String)
            End Get
            Set
                Me("RepositoryFolderPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SecondaryMasterFilePath() As String
            Get
                Return CType(Me("SecondaryMasterFilePath"),String)
            End Get
            Set
                Me("SecondaryMasterFilePath") = value
            End Set
        End Property
    End Class
End Namespace
